// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUFGxOItn8K7Td2ho5kFsh1pM0Iok1ig',
    appId: '1:1042335499343:web:4190fd29c7f8ae2f57d63a',
    messagingSenderId: '1042335499343',
    projectId: 'food-app-453de',
    authDomain: 'food-app-453de.firebaseapp.com',
    storageBucket: 'food-app-453de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9scIdFR5oaJhNfIkGMylkIeNxFOEeCKA',
    appId: '1:1042335499343:android:126dbb50166a948457d63a',
    messagingSenderId: '1042335499343',
    projectId: 'food-app-453de',
    storageBucket: 'food-app-453de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwJhJBM_J2vIvkTkwCzLkZQRpyMgHafvA',
    appId: '1:1042335499343:ios:4151796c310d73e757d63a',
    messagingSenderId: '1042335499343',
    projectId: 'food-app-453de',
    storageBucket: 'food-app-453de.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwJhJBM_J2vIvkTkwCzLkZQRpyMgHafvA',
    appId: '1:1042335499343:ios:4151796c310d73e757d63a',
    messagingSenderId: '1042335499343',
    projectId: 'food-app-453de',
    storageBucket: 'food-app-453de.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnUFGxOItn8K7Td2ho5kFsh1pM0Iok1ig',
    appId: '1:1042335499343:web:13392f42c57c4b8657d63a',
    messagingSenderId: '1042335499343',
    projectId: 'food-app-453de',
    authDomain: 'food-app-453de.firebaseapp.com',
    storageBucket: 'food-app-453de.appspot.com',
  );

}